### ISSUE TITLE
Validating / Enforcing Email Format

### ISSUE THREAD

**Issue by toucan-stan** [homework-bet/homework-bet#19]
We should probably enforce some sort of "x@y.z" structure to the user's email address; possibly as a validator in UserModel.

**Comment by sarahmaas** [comment]
Test if it even works with a bad format? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

**Comment by toucan-stan** [comment]
Hmm - our .ejs forms are just using 'text' input fields; should probably wait for the frontend to integrate before working further - would be good practice to validate in the backend as well, however.

**Comment by nathanperkins** [comment]
The best verification system is to send out an authorization token to the user's email and require them to accept it before allowing them to do anything dangerous, like pay for a course.

Until something like that is in place, we can probably grab a regex validator online, and use it in the backend right?

```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```

from http://emailregex.com/

**Comment by nathanperkins** [comment]
pr #35

**Comment by nathanperkins** [comment]
pr was merged
